 INSERT INTO flight_city (id, name, country, timezone) VALUES
 (1, 'Jacksonville', 'India', 'HKT'),
 (2, 'Washington, D.C.', 'South Korea', 'NST'),
 (3, 'New York', 'United States', 'UTC'),
 (4, 'Washington, D.C.', 'South Korea', 'NST'),
 (5, 'Charlotte', 'Russia', 'ADT'),
 (6, 'Jacksonville', 'India', 'HKT'),
 (7, 'Washington, D.C.', 'South Korea', 'ACST'),
 (8, 'Chicago', 'Mexico', 'NST'),
 (9, 'Seattle', 'Sweden', 'PST'),
 (10, 'Houston', 'United Kingdom', 'CET'),
 (11, 'Philadelphia', 'France', 'AWST'),
 (12, 'Chicago', 'Mexico', 'EST'),
 (13, 'Jacksonville', 'India', 'WET'),
 (14, 'Washington, D.C.', 'South Korea', 'ACST'),
 (15, 'San Jose', 'Japan', 'HKT'),
 (16, 'Washington, D.C.', 'South Korea', 'NST'),
 (17, 'Dallas', 'Brazil', 'NST'),
 (18, 'New York', 'United States', 'CST'),
 (19, 'Houston', 'United Kingdom', 'AST'),
 (20, 'Chicago', 'Mexico', 'UTC'),
 (21, 'Columbus', 'New Zealand', 'NZST'),
 (22, 'Charlotte', 'Russia', 'PST'),
 (23, 'Philadelphia', 'France', 'EET'),
 (24, 'San Jose', 'Japan', 'MST'),
 (25, 'Columbus', 'New Zealand', 'HKT'),
 (26, 'San Francisco', 'South Africa', 'NZST'),
 (27, 'Austin', 'China', 'EET'),
 (28, 'Fort Worth', 'Spain', 'JST'),
 (29, 'San Antonio', 'Italy', 'CET'),
 (30, 'Philadelphia', 'France', 'AST'),
 (31, 'San Antonio', 'Italy', 'AST'),
 (32, 'Denver', 'Singapore', 'JST'),
 (33, 'San Francisco', 'South Africa', 'WET'),
 (34, 'Los Angeles', 'Canada', 'EET'),
 (35, 'Charlotte', 'Russia', 'SGT'),
 (36, 'Columbus', 'New Zealand', 'GMT'),
 (37, 'Houston', 'United Kingdom', 'ADT'),
 (38, 'Chicago', 'Mexico', 'ACST'),
 (39, 'Chicago', 'Mexico', 'MSK'),
 (40, 'Columbus', 'New Zealand', 'PST'),
 (41, 'San Antonio', 'Italy', 'SGT'),
 (42, 'San Diego', 'Australia', 'PST'),
 (43, 'Austin', 'China', 'CET'),
 (44, 'Los Angeles', 'Canada', 'ACST'),
 (45, 'San Diego', 'Australia', 'GMT'),
 (46, 'Seattle', 'Sweden', 'IST'),
 (47, 'Austin', 'China', 'NZST'),
 (48, 'Indianapolis', 'Netherlands', 'WET'),
 (49, 'Indianapolis', 'Netherlands', 'WET'),
 (50, 'San Francisco', 'South Africa', 'SGT'),
 (51, 'Denver', 'Singapore', 'AST'),
 (52, 'Charlotte', 'Russia', 'CST'),
 (53, 'New York', 'United States', 'AST'),
 (54, 'San Francisco', 'South Africa', 'AST'),
 (55, 'San Jose', 'Japan', 'UTC'),
 (56, 'New York', 'United States', 'SGT'),
 (57, 'San Jose', 'Japan', 'UTC'),
 (58, 'Phoenix', 'Germany', 'ACST'),
 (59, 'San Francisco', 'South Africa', 'WET'),
 (60, 'New York', 'United States', 'CST'),
 (61, 'Jacksonville', 'India', 'IST'),
 (62, 'Columbus', 'New Zealand', 'HKT'),
 (63, 'Houston', 'United Kingdom', 'UTC'),
 (64, 'Fort Worth', 'Spain', 'HKT'),
 (65, 'Austin', 'China', 'EST'),
 (66, 'Chicago', 'Mexico', 'EET'),
 (67, 'Columbus', 'New Zealand', 'AST'),
 (68, 'Dallas', 'Brazil', 'HKT'),
 (69, 'Phoenix', 'Germany', 'EST'),
 (70, 'Columbus', 'New Zealand', 'NZST'),
 (71, 'Fort Worth', 'Spain', 'PST'),
 (72, 'Charlotte', 'Russia', 'HKT'),
 (73, 'Chicago', 'Mexico', 'MSK'),
 (74, 'Indianapolis', 'Netherlands', 'ACST'),
 (75, 'Philadelphia', 'France', 'CST'),
 (76, 'Seattle', 'Sweden', 'MSK'),
 (77, 'Dallas', 'Brazil', 'WET'),
 (78, 'New York', 'United States', 'EET'),
 (79, 'Seattle', 'Sweden', 'ADT'),
 (80, 'San Francisco', 'South Africa', 'PST'),
 (81, 'San Jose', 'Japan', 'IST'),
 (82, 'Washington, D.C.', 'South Korea', 'SGT'),
 (83, 'Fort Worth', 'Spain', 'IST'),
 (84, 'San Francisco', 'South Africa', 'CST'),
 (85, 'Charlotte', 'Russia', 'ACST'),
 (86, 'Indianapolis', 'Netherlands', 'JST'),
 (87, 'Jacksonville', 'India', 'AST'),
 (88, 'Los Angeles', 'Canada', 'UTC'),
 (89, 'San Jose', 'Japan', 'NZST'),
 (90, 'San Antonio', 'Italy', 'ACST'),
 (91, 'Jacksonville', 'India', 'ADT'),
 (92, 'Washington, D.C.', 'South Korea', 'NST'),
 (93, 'Los Angeles', 'Canada', 'EET'),
 (94, 'Chicago', 'Mexico', 'SGT'),
 (95, 'Houston', 'United Kingdom', 'ADT'),
 (96, 'Los Angeles', 'Canada', 'GMT'),
 (97, 'Indianapolis', 'Netherlands', 'ACST'),
 (98, 'Charlotte', 'Russia', 'HKT'),
 (99, 'Columbus', 'New Zealand', 'EET'),
 (100, 'Jacksonville', 'India', 'NST');

 INSERT INTO flight_airport (id, city_id, iata_code, icao_code, description, site) VALUES
 (1, 93, 'ZCP', 'KIMF', 'Praeclaram beate vivendi et apertam et simplicem et directam viam! Cum enim certe nihil homini possit melius esse quam Graecam. Quando enim nobis, vel dicam aut oratoribus bonis aut poetis, postea quidem.', 'JNARwytVBI'),
 (2, 48, 'UDP', 'HRDW', 'Quam ostendis. Sed uti oratione perpetua malo quam.', 'cXih'),
 (3, 54, 'MJJ', 'UJWN', 'Adipiscing elit, sed do eiusmod tempor incididunt ut labore et.', 'uEiKTUMp'),
 (4, 65, 'CQG', 'ICBP', 'Torquatis.'' Numquam hoc ita defendit Epicurus neque Metrodorus aut quisquam eorum, qui aut saperet aliquid aut ista didicisset. Et quod adest sentire possumus, animo autem et praeterita grate meminit et.', 'sZI'),
 (5, 49, 'DDE', 'XWWP', 'Petat aut fugiat aliquid, praeter voluptatem et parvam et non necessariam et quae fugiamus refert.', 'tHeSaAPd'),
 (6, 13, 'BYX', 'BJUL', 'Vellem, censes haec dicturum fuisse? Utrum igitur percurri omnem Epicuri disciplinam placet an de una voluptate quaeri, de qua Epicurus quidem ita.', 'EUOquAcP'),
 (7, 30, 'OEV', 'GOMB', 'Ad quam omnia iudicia rerum dirigentur, numquam ullius oratione victi sententia desistemus. Nisi autem rerum natura duo quaerenda sint, unum, quae materia sit, ex qua quaeque res efficiatur, alterum, quae naturales essent nec tamen id, cuius causa haec finxerat.', 'Fuxh'),
 (8, 40, 'ESN', 'OIUH', 'Vitae degendae et rerum gerendarum. Sic e physicis et fortitudo sumitur contra mortis.', 'Rfl'),
 (9, 61, 'UBQ', 'JLZG', 'Omni sale idem Lucilius, apud quem praeclare Scaevola: Graecum te, Albuci, quam Romanum atque Sabinum, municipem Ponti, Tritani, centurionum, praeclarorum hominum ac primorum signiferumque, maluisti dici. Graece ergo praetor Athenis, id quod maluisti, te, cum ad me de virtute misisti. Sed ex eo credo quibusdam usu venire, ut.', 'TTE'),
 (10, 90, 'SDQ', 'WQSE', 'Non sunt vituperandae, maledicta, contumeliae, tum iracundiae, contentiones concertationesque in disputando pertinaces.', 'ZaTkQbjF'),
 (11, 63, 'NQU', 'UUTU', 'Est, cum esset accusata et vituperata ab.', 'SsQiTTon'),
 (12, 50, 'SIQ', 'LWHQ', 'In morbos gravis, tum in morbos gravis, tum in dedecora incurrunt, saepe etiam videmus, et perspicuum est nihil desiderare manum, cum ita esset affecta, secundum non.', 'OgsK'),
 (13, 31, 'WFL', 'WQVT', 'Et factis et moribus comprobavit. Quod quam magnum sit.', 'zfgzhgqE'),
 (14, 35, 'PMP', 'GWEN', 'De philosophia litteris mandamus, legere assueverit, iudicabit nulla ad.', 'DlTR'),
 (15, 44, 'ADI', 'ZUOC', 'Quo sint omnia bene vivendi recteque faciendi consilia referenda, quid sequatur natura ut summum malum et, quantum possit, a se.', 'DTyqvADY'),
 (16, 86, 'MAQ', 'JKVA', 'Omnia dixi hausta e fonte naturae, si tota oratio nostra omnem sibi fidem sensibus confirmat, id est incorruptis atque integris testibus, si infantes pueri, mutae etiam bestiae paene loquuntur magistra ac duce natura nihil esse maius.', 'IUlktUD'),
 (17, 13, 'MNE', 'DYZY', 'Regula et iudicio ab eadem illa individua et solida corpora ferri deorsum suo pondere ad lineam, hunc naturalem esse omnium corporum motum. Deinde ibidem.', 'utXI'),
 (18, 27, 'ZBT', 'PWMZ', 'Redeamus, de hominibus dici non modo fautrices fidelissimae.', 'CQsi'),
 (19, 91, 'NNT', 'LXDI', 'His esse potiora. Quid est cur verear, ne ad eam non possim accommodare Torquatos nostros? Quos tu paulo ante cum memoriter, tum etiam erga.', 'PzulIPKt'),
 (20, 10, 'GQM', 'VDVH', 'Omni virtute sit dictum. Sed similia fere dici possunt. Ut enim mortis metu omnis quietae vitae status perturbatur, et ut succumbere doloribus eosque humili.', 'WBiT'),
 (21, 41, 'HXV', 'EDYI', 'Consuevit iactare vestra se oratio, tua praesertim, qui studiose antiqua.', 'xDjq'),
 (22, 99, 'BTW', 'KRRI', 'Eripuit atomis nec tamen necessariae, tertium, quae nec naturales nec necessariae. Quarum.', 'TRkiNncuqo'),
 (23, 52, 'EIO', 'TSLA', 'Successerit, eoque intellegi potest quanta voluptas sit non dolere. Sed ut omittam pericula, labores, dolorem etiam, quem optimus quisque pro patria et pro suis suscipit, ut non dicas, quid non probes. Principio, inquam, in physicis, quibus.', 'APU'),
 (24, 11, 'RQL', 'KZWN', 'Graviterque comprehenderit, ut omnes bene sanos ad iustitiam, aequitatem, fidem, neque homini infanti aut inpotenti iniuste facta conducunt, qui nec facile efficere possit, quod conetur, nec optinere, si effecerit, et opes vel fortunae vel ingenii liberalitati magis conveniunt, qua qui est imbutus.', 'rtgBTz'),
 (25, 72, 'KZV', 'SFNW', 'A Scaevola est praetore salutatus Athenis Albucius. Quem quidem locum.', 'vHT'),
 (26, 96, 'IKM', 'KXND', 'Poetis evolvendis, ut ego et Triarius te hortatore facimus, consumeret, in quibus sequitur Democritum, non fere labitur. Quamquam utriusque cum multa non probo, tum illud in primis, quod, cum in rerum natura.', 'SbLJfTL'),
 (27, 17, 'WAN', 'SAEP', 'Et voluptatem, illud enim ipsum, quod quibusdam medium videretur, cum.', 'urLjs'),
 (28, 58, 'ZYO', 'DGEZ', 'Quod quibusdam medium videretur, cum omni dolore careret, non modo non repugnantibus, verum etiam summam voluptatem. Quisquis enim sentit, quem ad modum temeritas et libido et ignavia semper animum excruciant et semper.', 'wNJh'),
 (29, 6, 'YXG', 'OOLS', 'Depravare videatur. Ille atomos quas appellat, id est voluptatem. Homines optimi non intellegunt totam rationem everti, si ita melius sit, migrare de vita. His rebus instructus semper est in voluptate.', 'INWdiV'),
 (30, 31, 'XDK', 'FMQA', 'Quibus ego assentior, cum a philosophis compluribus permulta dicantur, cur nec voluptas in bonis sit numeranda nec in discordia dominorum domus, quo minus animus a se repellere, idque facere nondum depravatum ipsa natura.', 'aePlNsT'),
 (31, 16, 'HJM', 'FODP', 'Spernat aut reiciat, quod se isdem Euripidis fabulis delectari dicat, Latinas litteras oderit? Synephebos ego, inquit, potius Caecilii aut Andriam Terentii quam utramque Menandri legam? A quibus tantum.', 'UineEi'),
 (32, 55, 'XQH', 'BVES', 'Nisi te audire vellem, censes haec dicturum fuisse? Utrum igitur percurri omnem Epicuri disciplinam placet an de una voluptate quaeri, de qua Epicurus quidem ita dicit, omnium rerum.', 'FJfiwmDU'),
 (33, 19, 'ZCU', 'ULLQ', 'Reliqui nihil est, necesse est, non expeteretur, si nihil efficeret, nunc expetitur, quod est tamquam.', 'VpayjwL'),
 (34, 36, 'JYK', 'RAPA', 'Natura, non potest esse dubium.', 'jFq'),
 (35, 1, 'GTF', 'WUPA', 'Alii minuti et angusti aut omnia semper desperantes aut malivoli, invidi, difficiles.', 'eAg'),
 (36, 17, 'TUR', 'LRMW', 'Conturbamur ignoratione rerum, e qua.', 'fugR'),
 (37, 97, 'VGA', 'EMZA', 'Ne movere hominum studia viderer, retinere non posse. Qui autem, si maxime hoc placeat, moderatius tamen id volunt fieri, difficilem quandam temperantiam postulant in.', 'vRE'),
 (38, 66, 'AKF', 'ZECR', '-- Nihil sane. -- ''At, si.', 'xnUN'),
 (39, 4, 'VZM', 'WSCV', 'Causa sunt, qua ante quam nati, et ad usus civium non inutile, nosque ea scripta reliquaque eiusdem generis et legimus libenter et legemus --, haec, quae de philosophia litteris mandamus.', 'MtgW'),
 (40, 36, 'AMQ', 'GSQF', 'Ex infinito tempore aetatis percipi posse, quam ex hoc percipiatur, quod videamus esse finitum. In dialectica autem vestra nullam existimavit esse nec ad commodius disserendum viam. In physicis plurimum posuit. Ea scientia et verborum vis et natura orationis et consequentium repugnantiumve ratio.', 'oBJXgAO'),
 (41, 87, 'OZH', 'RCBH', 'Placet ac leniat. Temperantia est enim, quae in rebus aut expetendis aut fugiendis ut rationem sequamur monet. Nec enim habet nostra mens quicquam, ubi consistat tamquam in extremo, omnesque et.', 'LzUXLxABsd'),
 (42, 13, 'CCV', 'VKMR', 'Nihil homini possit melius esse quam vacare omni dolore.', 'JQrotSHNpH'),
 (43, 82, 'WAS', 'AHOQ', 'Habet, inanium autem cupiditatum nec modus ullus nec finis inveniri potest. Quodsi.', 'TkICXWzolb'),
 (44, 11, 'HYK', 'HXOX', 'Semper impendet, tum superstitio, qua qui affecti sunt in culpa, qui officia deserunt mollit anim id est vel summum bonorum vel ultimum vel extremum -- quod Graeci telos nominant --, quod ipsum nullam ad aliam rem.', 'QsQCZd'),
 (45, 50, 'RME', 'ZGYT', 'Et vacuitate omnis molestiae gaudemus, omne autem id, quo gaudemus, voluptas est, ut meminerit maximos morte finiri, parvos multa habere intervalla requietis, mediocrium nos esse dominos.', 'UbeuRtnFi'),
 (46, 49, 'RYX', 'GDNL', 'Insitam in animis nostris inesse notionem, ut alterum esse appetendum, alterum aspernandum.', 'CERYmS'),
 (47, 52, 'RWZ', 'TPOL', 'Et expedita distinctio. Nam libero tempore, cum soluta nobis est.', 'mmVmx'),
 (48, 17, 'XNR', 'HBEW', 'Sinat. Qua praeceptrice in tranquillitate vivi potest omnium cupiditatum ardore restincto. Cupiditates enim sunt insatiabiles, quae non modo nullam captet, sed etiam quid a singulis philosophiae disciplinis diceretur, persecuti sumus. Ut autem a.', 'SfRS'),
 (49, 88, 'VRR', 'QTAM', 'Iucunda, per se ipsam causam non multo maiores esse et muniti videntur, deorum tamen horrent easque ipsas sollicitudines, quibus eorum animi noctesque diesque exeduntur.', 'jdKQ'),
 (50, 92, 'SGH', 'VSRK', 'Melius esse quam vacare omni dolore careret, non modo quid nobis probaretur, sed etiam cogitemus, infinitio ipsa, quam.', 'LGKnviWXkN'),
 (51, 13, 'QTC', 'LATC', 'Confidet fore semper occultum. Plerumque improborum facta primo suspicio insequitur, dein sermo atque fama, tum accusator, tum iudex.', 'bJQhBddB'),
 (52, 70, 'LGH', 'GNKL', 'Occultum. Plerumque improborum facta primo suspicio insequitur, dein sermo atque fama, tum accusator, tum iudex, Multi etiam, ut.', 'ZXitqZC'),
 (53, 51, 'KES', 'FBXX', 'Omnium rerum occultarum ignoratione sublata et moderatio natura cupiditatum generibusque.', 'MgHjaj'),
 (54, 69, 'SLJ', 'CGNF', 'Quam cum omnia in philosophia, tum id, quod propositum est, summum profecto malum est vivere cum dolore, cui sententiae consentaneum.', 'UDWvwKu'),
 (55, 27, 'OUA', 'ZLUS', 'Prorsus existimo, neque eum Torquatum, qui hoc primus cognomen.', 'EpRC'),
 (56, 78, 'KWC', 'CHQQ', 'Denique'' -- non enim illum ab industria, sed.', 'zWlBihHwLa'),
 (57, 63, 'NCU', 'FZXE', 'Sola, quae nos vocet ad se et Consentinis et Siculis scribere. Facete is quidem, sicut alia, sed neque tam docti tum erant, ad quorum.', 'RIe'),
 (58, 73, 'KTR', 'BYFY', 'At magnum periculum adiit. -- In oculis quidem exercitus. -- Quid ex eo est.', 'RkkmbnISyJ'),
 (59, 9, 'CJC', 'MNEB', 'Vivendum aptior partitio quam illa, qua est usus Epicurus? Qui.', 'FfIvICYp'),
 (60, 24, 'WHZ', 'VTLB', 'Adipiscuntur praetermittenda voluptate. Idem etiam dolorem saepe perpetiuntur, ne, si id non faciant, incidant in maiorem. Ex quo intellegitur nec timiditatem ignaviamque vituperari nec fortitudinem patientiamque laudari suo nomine, sed illas reici, quia.', 'maZ'),
 (61, 75, 'TSW', 'JNFO', 'Militaris imperii disciplinam exercitumque in gravissimo bello animadversionis metu contineret, saluti prospexit civium, qua intellegebat contineri suam. Atque haec ratio late patet. In quo enim maxime consuevit iactare vestra se oratio, tua praesertim, qui studiose antiqua persequeris, claris et fortibus viris commemorandis eorumque factis.', 'uNBdz'),
 (62, 85, 'GOT', 'YANN', 'Parvos multa habere intervalla requietis, mediocrium nos esse dominos, ut, si tolerabiles sint, feramus, si minus, animo aequo e vita, cum ea non placeat, tamquam e theatro exeamus. Quibus rebus intellegitur nec intemperantiam propter se expetendam esse dicemus, sed quia pacem animis afferat et eos quasi concordia quadam.', 'FiwlKEkc'),
 (63, 22, 'YEZ', 'IOIB', 'Umbram, quod appellant honestum non tam solido quam splendido nomine, virtutem autem.', 'wqoSV'),
 (64, 5, 'ALG', 'UYAG', 'Quidem virtutum laus, in qua maxime ceterorum philosophorum exultat oratio, reperire exitum potest, nisi derigatur ad voluptatem, voluptas autem est sola, quae nos exhorrescere metu non sinat. Qua praeceptrice in tranquillitate vivi potest omnium cupiditatum ardore restincto. Cupiditates enim sunt insatiabiles, quae non modo non repugnantibus, verum etiam.', 'xid'),
 (65, 26, 'JNJ', 'VNFJ', 'Certe audiam, quid sit, quod Epicurum nostrum non tu quidem oderis, ut fere faciunt, qui ab eo delectari, quod ista.', 'JlRnCh'),
 (66, 57, 'ZZH', 'VVQV', 'Medium videretur, cum omni dolore detracto, nam quoniam, cum privamur dolore, ipsa liberatione et vacuitate omnis molestiae gaudemus, omne autem id, quo gaudemus, voluptas est, ut necessariae nec opera multa nec impensa.', 'daazIFUy'),
 (67, 89, 'FCS', 'XCYU', 'Posse reperiri. Quapropter si ea, quae sensum moveat, nulla.', 'yrCSPMdp'),
 (68, 86, 'UUX', 'ZMIB', 'Liberavisse et omnia tradidisse, quae pertinerent ad bene vivendum aptior partitio quam illa, qua est usus Epicurus? Qui unum genus.', 'cbGVfqYNw'),
 (69, 73, 'INJ', 'AGEV', 'Omne oritur a sensibus, qui si omnes atomi declinabunt, nullae umquam cohaerescent, sive aliae declinabunt, aliae suo nutu recte ferentur, primum erit hoc quasi, provincias atomis dare, quae recte, quae oblique ferantur.', 'LoFoePEpv'),
 (70, 96, 'CXE', 'LFTJ', 'Consentaneum est ultimum esse bonorum voluptatem ex infinito tempore aetatis percipi posse, quam ex hoc facillime perspici potest: Constituamus aliquem magnis, multis, perpetuis fruentem et animo et attento intuemur, tum fit ut aegritudo sequatur, si illa mala sint, laetitia, si bona. O praeclaram beate vivendi et apertam et simplicem et directam viam! Cum enim certe nihil.', 'gKcQlGrhuR'),
 (71, 55, 'JPC', 'CXGU', 'Quibus ego assentior, dum modo de isdem rebus ne Graecos quidem legendos.', 'CxVx'),
 (72, 17, 'GKP', 'QOQU', 'Si ita res se habeat. Nam si ea sola voluptas esset, quae quasi titillaret.', 'KYdpktvd'),
 (73, 80, 'GPW', 'YYSS', 'Perfecto, huic pedalis fortasse, tantum enim esse censet, quantus videtur, vel paulo aut maiorem.', 'TZi'),
 (74, 83, 'RFM', 'LVTO', 'Principio, inquam, in physicis, quibus maxime gloriatur, primum totus est alienus. Democritea dicit perpauca mutans, sed ita, ut ea, quae hoc non minus declarant, sed videntur leviora, veniamus. Quid tibi, Torquate, quid huic.', 'SnaoI'),
 (75, 49, 'RSE', 'GIMF', 'Domus, quo minus id, quod quaeritur, sit pulcherrimum. Etenim si loca, si fana, si urbes, si gymnasia, si campum, si canes, si equos, si ludicra exercendi aut venandi consuetudine adamare solemus, quanto id in voluptate ponatur, sed sine hoc institutionem omnino amicitiae non posse.', 'Ayj'),
 (76, 6, 'ODS', 'RVMY', 'Non inhumanus, qui novum vicinum non vult ''fodere aut arare aut aliquid ferre denique'' -- non enim illum ab industria, sed ab inliberali labore.', 'KGdRlCzkhT'),
 (77, 10, 'VUH', 'IRGH', 'Tam solido quam splendido nomine, virtutem autem nixam hoc honesto nullam requirere voluptatem atque ad beate vivendum sapientia comparaverit, nihil esse.', 'ZrMYQPIi'),
 (78, 12, 'PCP', 'JFEK', 'Dicam, et ad tranquillitatem ferant, quid est cur tam multos legant, quam legendi sunt. Quid enim me prohiberet Epicureum esse, si probarem, quae ille.', 'BotMzPLEXL'),
 (79, 1, 'IGN', 'NCZE', 'Potest. Atqui pugnantibus et contrariis studiis consiliisque semper utens nihil quieti videre, nihil tranquilli.', 'FtxUBYNA'),
 (80, 29, 'XID', 'ZDRQ', 'Nulla est intercapedo molestiae. Igitur neque stultorum quisquam.', 'eymdzJNKs'),
 (81, 31, 'FPY', 'CMJO', 'Maximos morte finiri, parvos multa habere intervalla requietis, mediocrium nos esse dominos, ut, si tolerabiles sint, feramus, si.', 'hGMwsQ'),
 (82, 31, 'ZJM', 'TIKK', 'Ad iucunde vivendum reperiri posse.', 'KnWm'),
 (83, 49, 'TAB', 'ZMBS', 'Neque divinum numen horreat nec praeteritas voluptates effluere patiatur earumque assidua recordatione laetetur, quid est, cur nostri a nostris de amicitia disputatum. Alii cum eas voluptates, quae ad quietem et ad tranquillitatem ferant, quid est enim contra Cyrenaicos satis.', 'AYlSRah'),
 (84, 27, 'IHB', 'KHVR', 'Concursio hunc mundi ornatum efficere non poterit. Ne illud quidem perspicuum est, maximam animi aut voluptatem aut molestiam plus aut ad bene beateque vivendo a Platone disputata sunt.', 'XGAc'),
 (85, 88, 'PFO', 'GFTW', 'Quid iudicat, quo aut petat aut fugiat aliquid, praeter voluptatem et dolorem? Sunt autem.', 'ZqJSD'),
 (86, 11, 'KME', 'PZGJ', 'Dolores autem si qui incurrunt, numquam vim tantam habent, ut non dicas, quid non probes. Principio, inquam, in.', 'srzHCRJN'),
 (87, 53, 'OAG', 'MFMW', 'Ne minus amicos quam se ipsos diligant. Quod et acutum genus est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id.', 'RRDnrYH'),
 (88, 100, 'IER', 'WPYU', 'Profecto malum est vivere cum dolore, cui sententiae consentaneum est ultimum esse bonorum eum voluptate vivere. Huic certae stabilique sententiae quae sint.', 'DkBiD'),
 (89, 73, 'GFB', 'AUSQ', 'Ordiamur, prima veniat in medium Epicuri ratio, quae plerisque notissima est. Quam a nobis sic intelleges eitam, ut ab ea nullo modo poterimus sensuum.', 'VeQC'),
 (90, 52, 'UYV', 'ZYLO', 'Philosophia mihi videri solent. Tum Torquatus: Prorsus, inquit, assentior, neque enim tempus est ullum, quo non plus habeat sapiens, quod gaudeat, quam quod angatur. Optime vero.', 'zgMBNwY'),
 (91, 55, 'ZLH', 'FYKM', 'Nam et praeterita et futura. Ut enim virtutes, de quibus neque depravate iudicant.', 'sRDrAlPAe'),
 (92, 48, 'MIB', 'KUMC', 'Numeris, astris contereret, quae et terroribus cupiditatibusque detractis et omnium falsarum opinionum temeritate derepta certissimam se nobis ducem praebeat ad voluptatem. Sapientia enim est a Chrysippo praetermissum.', 'kCRjEfmRVU'),
 (93, 64, 'FYP', 'ZAAF', 'Cur tam multos legant, quam legendi sunt. Quid enim me prohiberet Epicureum esse, si probarem, quae ille diceret? Cum praesertim illa perdiscere ludus esset.', 'CHZNxIDLrE'),
 (94, 52, 'DBR', 'KNAY', 'Ipsum dedocere. Sol Democrito magnus videtur, quippe homini erudito in geometriaque perfecto, huic pedalis fortasse, tantum enim esse omnino in nostris poetis aut inertissimae.', 'GNUrkD'),
 (95, 2, 'EJQ', 'EYJZ', 'Nostris de amicitia disputatum. Alii cum eas voluptates, quae ad quietem et.', 'wTQC'),
 (96, 57, 'MIP', 'IQCT', 'Cognosci et percipi. Quos qui tollunt et nihil posse percipi dicunt, ii remotis sensibus ne id ipsum quidem expedire possunt, quod disserunt. Praeterea sublata cognitione et scientia.', 'BWvIamL'),
 (97, 36, 'OHL', 'KGKJ', 'Autem, qui dicant foedus esse quoddam sapientium, ut ne minus amicos quam se ipsos penitus perdiderunt, sic robustus animus et a spe pariendarum voluptatum seiungi non potest.', 'guA'),
 (98, 78, 'BNK', 'HKXZ', 'Ille, sciscat et probet, id est incorruptis atque integris testibus, si infantes pueri, mutae etiam bestiae paene loquuntur magistra ac duce natura nihil esse maius amicitia, nihil uberius, nihil iucundius. Nec vero quisquam stultus non horum morborum aliquo laborat, nemo igitur est difficilius satis facere, qui se Latina.', 'yXCXMxzZv'),
 (99, 61, 'CNX', 'FQFJ', 'Erigimur, quae expectamus, sic laetamur iis, quae recordamur. Stulti autem malorum memoria torquentur, sapientes bona praeterita grata recordatione renovata delectant. Est autem situm in nobis ut et adversa quasi perpetua oblivione obruamus et secunda iucunde ac suaviter meminerimus. Sed.', 'mwQzZKiOF'),
 (100, 21, 'RLE', 'ISOF', 'Similia fere dici possunt. Ut enim mortis metu omnis quietae vitae.', 'kzlMaqnn');

